ticket_quartal = {
    # Индексы
    'Index_RTS': ['RI', 'Q'],
    'Index_S&P_500':['SF','Q'],
    'Index_MOEX_mini':['MM','Q'],
    'Index_NASDQ':['NA','Q'],
    'Index_MOEX':['MX','Q'],
    'Index_RTS_mini':['RM','Q'],
    'Index_RGBI':['RB','Q'],
    'Index_RVI':['VI','NM'],
    'Index_Consumer_sector':['CS','Q'],
    'Index_Metals&mining':['MA','Q'],
    'Index_Brent&Gaz':['OG','Q'],
    'Index_Finance':['FN','Q'],
    'Index_DomClick':['HO','Q'],
    # Фьючерсы на акции
    'SBERBANK':['SR','Q'],
    'GAZPROM':['GZ','Q'],
    'VTB':['VB','Q'],
    'NORILSK_NICKEL':['GK','Q'],
    'POLYMETAL':['PO','Q'],
    'YANDEX':['YN','Q'],
    'LUKOIL':['LK','Q'],
    'SBERBANK_PREF':['SP','Q'],
    'MAILRU':['ML','Q'],
    'MAGNIT':['MN','Q'],
    'ROSNEFT':['RN','Q'],
    'NLMK':['NM','Q'],
    'ALROSA':['AL','Q'],
    'RUSAL':['RL','Q'],
    'SURGUTNEFTEGAZ':['SN','Q'],
    'POLYUS':['PZ','Q'],
    'TCS_GROUP':['TI','Q'],
    'MOSBIRZHA':['ME','Q'],
    'RUSGYDRO':['HY','Q'],
    'AEROFLOT':['AF','Q'],
    'X5':['FV','Q'],
    'SAMOLET':['SS','Q'],
    'OZON':['OZ','Q'],
    'MTS':['MT','Q'],
    'PHOSAGRO':['PH','Q'],
    'MMK':['MG','Q'],
    'PIK':['PI','Q'],
    'AFK_SISTEMA':['AK','Q'],
    'TATNEFT':['TT','Q'],
    'SEVERSTAL':['CH','Q'],
    'NOVATEK':['NK','Q'],
    'FSK_EES':['FS','Q'],
    'SURGUTNEFTEGAZ_PREF':['SG','Q'],
    'INTER_RAO_EES':['IR','Q'],
    'ROSTELECOM':['RT','Q'],
    'GAZPROM_NEFT':['SO','Q'],
    'SPB_BIRZHA':['SE','Q'],
    'DETSKII_MIR':['DY','Q'],
    'MECHEL':['MC','Q'],
    'ROSSIJSKIE_SETI':['RE','Q'],
    'TRANSNEFT':['TN','Q'],
    # Валюта
    'UAN/RUB':['CR','Q'],
    'USD/RUB':['Si','Q'],
    'EUR/RUB':['Eu','Q'],
    'EUR/USD':['ED','Q'],
    'USD/JPY':['JP','Q'],
    'GBP/USD':['GU','Q'],
    'AUD/USD':['AU','Q'],
    'USD/CAD':['CA','Q'],
    'USD/CHF':['CF','Q'],
    'EUR/CAD':['EC','Q'],
    'EUR/GBP':['EG','Q'],
    'EUR/JPY':['EJ','Q'],
    # Товарные контракты
    'NATURALGAZ':['NG','CM'],
    'GOLD':['GD','Q'],
    'BRENT':['BR','NM'],
    'SILVER':['SV','Q'],
    'PLATINUM':['PT','Q'],
    'PALLADIUM':['PD','Q'],
    'WHEAT':['W4','CM'],
    'ALUMINUM':['AM','NM'],
    'COPPER':['Co','NM'],
    'GOLD_SUPPLY':['GO','NM'],
    'NICKEL':['Nl','NM'],
    'SILVER_SUPPLY':['SL','NM'],
    'ZINC':['Zn','NM']
}

unit_month = { 1:'F', 2:'G', 3:'H', 4:'J', 5:'K', 6:'M', 7:'N', 8:'Q', 9:'U', 10:'V', 11:'X', 12:'Z'}